### ISSUE TITLE
Shears not working

### ISSUE THREAD

**Issue by janaron** [btwonion/magnetic#22]
Shears are not working on my server and in the error message magnetic pops up. Could you look into it?

```
[10:10:44] [Server thread/ERROR]: Failed to handle packet net.minecraft.class_2824@42bd5e8b, suppressing error
com.llamalad7.mixinextras.injector.wrapoperation.IncorrectArgumentCountException: Incorrect number of arguments passed to Operation::call! Expected 4 but got 2. Expected types were [net.minecraft.class_1472, net.minecraft.class_3218, net.minecraft.class_3419, net.minecraft.class_1799], actual types were [net.minecraft.class_1472, net.minecraft.class_3419].
	at knot/com.llamalad7.mixinextras.injector.wrapoperation.WrapOperationRuntime.checkArgumentCount(WrapOperationRuntime.java:10) ~[mixinextras-0.4.1-215bdc40eef77b8f.jar:?]
	at knot/net.minecraft.class_1472.mixinextras$bridge$method_6636$41(class_1472.java) ~[server-intermediary.jar:?]
	at knot/dev.nyon.magnetic.utils.MixinHelper.prepareShearableServerPlayer(MixinHelper.java:160) ~[magnetic-3.2.0-1.21.2.jar:?]
	at knot/net.minecraft.class_1472.wrapOperation$bpi000$magnetic$prepareThreadLocalForShearing(class_1472.java:555) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_1472.method_5992(class_1472.java:180) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_1308.method_5688(class_1308.java:1263) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_1657.method_7287(class_1657.java:1095) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_3244$1.method_33897(class_3244.java:1645) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_3244$1.method_34219(class_3244.java:1657) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_2824$class_5909.method_34213(class_2824.java:124) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_2824.method_34209(class_2824.java:74) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_3244.method_12062(class_3244.java:1638) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_2824.method_12251(class_2824.java:61) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_2824.method_11054(class_2824.java:15) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_2600.method_11072(class_2600.java:27) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_3738.run(class_3738.java:18) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_1255.method_18859(class_1255.java:164) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_4093.method_18859(class_4093.java:23) ~[server-intermediary.jar:?]
	at knot/net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:889) ~[server-intermediary.jar:?]
	at knot/net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:180) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_1255.method_16075(class_1255.java:138) ~[server-intermediary.jar:?]
	at knot/net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:871) ~[server-intermediary.jar:?]
	at knot/net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:865) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_1255.method_18857(class_1255.java:147) ~[server-intermediary.jar:?]
	at knot/net.minecraft.server.MinecraftServer.method_18857(MinecraftServer.java:829) ~[server-intermediary.jar:?]
	at knot/net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:836) ~[server-intermediary.jar:?]
	at knot/net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:719) ~[server-intermediary.jar:?]
	at knot/net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:292) ~[server-intermediary.jar:?]
```

**Comment by btwonion** [comment]
Thanks for the report. I will look into it in the coming days.
